% Copyright 2017 Elgiz Baskaya

% This file is part of curedRone.

% curedRone is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
% 
% curedRone is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with curedRone.  If not, see <http://www.gnu.org/licenses/>.

% Figures for DASC 2017
subplot(2,1,1);
plot(ti : ti : sim_duration_min * 60, control_input(1, 1 : length(control_input) - 1));
ylabel({'$\delta_a [^{\circ}]$'},... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',18,... 
    'FontName','Times')
xlabel('time[s]',... 
    'FontUnits','points',... 
    'FontWeight','normal',...
    'FontSize',17,... 
    'FontName','Times')
axis([0 sim_duration_min * 60 0 5])

subplot(2,1,2);
plot(ti : ti : sim_duration_min * 60, sensor_sim_out(1, 1 : length(control_input) - 1));
ylabel({'$acc_x [m/s^2]$'},... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',18,... 
    'FontName','Times')
xlabel('time[s]',... 
    'FontUnits','points',... 
    'FontWeight','normal',...
    'FontSize',17,... 
    'FontName','Times')


print -depsc2 control_input_acc_x.eps